
#! ตั้งค่าต่างๆ
app:
  name: "TestApp"
  version: "0.0.1"
  state: "LOCAL"#LOCAL, DEV, SIT, UAT, PROD
  timezone: "Asia/Bangkok"
  config:
    host: "localhost"
    port: 8080
    path: "/api"
    allows:
      origins:
        - "*"
      response:
        error: true

#! อันนี้ฐานข้อมูล
database:
  postgres:
    dbname: "mydb"
    host: "34.142.241.45"
    port: 5432
    username: "admin"
    password: "admin123"
