
#! ตั้งค่าต่างๆ
app:
  name: "TestApp"
  version: "0.0.1"
  state: "LOCAL"#LOCAL, DEV, SIT, UAT, PROD
  timezone: "Asia/Bangkok"
  config:
    host: "localhost"
    port: 8080
    path: "/api"
    allows:
      origins:
        - "*"
      response:
        error: true

#! อันนี้ฐานข้อมูล
database:
  postgres:
    dbname: "service_login"
    host: "ep-ancient-mouse-a1ew8pnp-pooler.ap-southeast-1.aws.neon.tech"
    port: 5432
    username: "service_login_owner"
    password: "npg_CcjJINs4wr0W"
